version: '3'
services:
#
#  mysql_server:
#    image: mysql
#    container_name: container_mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#      MYSQL_DATABASE: ${DB_NAME}
#    restart: always
#    ports:
#      - "3306:3306"

  mysql_server:
    image: mysql
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_PASSWORD: "123"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "turbocrawler"
    restart: always
    ports:
      - "3306:3306"
